version: "3.3"

services:
  db:
    image: postgres:10.0
    networks:
      feedo-network:
    env_file: .env

  application:
    image: feedo
    build: ./feedo
    env_file: .env
    entrypoint: /install_resources/start.sh
    networks:
      feedo-network:
        aliases:
          - uwsgihost
    depends_on:
      - db

  nginx:
    image: nginx
    env_file: .env
    networks:
      feedo-network:
    depends_on:
      - application
    ports:
      - 80:80
    volumes:
      - ./feedo/install_resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  rabbit:
    image: rabbitmq:3-management
    networks:
      feedo-network:
        aliases:
          - rabbit
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    image: feedo:latest
    networks:
      feedo-network:
    env_file: .env
    entrypoint: /install_resources/celery.sh
    depends_on:
      - rabbit

volumes:
  db_volume:

networks:
  feedo-network:
    driver: bridge
